<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Home</title>
		<link rel="shortcut icon" href="img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar2.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				
				
				
				  <div class="row-fluid">
					<div class="span6" style="text-align:center;" >
					  <!--Sidebar content-->
						<img style="max-width: 436px;margin-top: -20px;" src="<?php echo $this->baseUrl()?>/img/logoImecNegro.png" />	
						<h1><div style="color: lightSkyBlue;font-weight: bold;line-height: 1.2;text-shadow: 0 2px 3px black;font-family: Istok Web, helvetica;font-size: 38px;">Hoy 50% descuento en Matricula.</div></h1>
							<br>
						<button class="btn btn-info" href="#">Matriculate ahora</button>						
					</div>
					<div class="span6">
					  <!--Body content-->
						<div style="margin-top: 21px; width: 428px;    margin: 0 auto;">
							<div id="myCarousel" class="carousel slide">
								<div class="carousel-inner">
								  <div class="active item">
									<img src="<?php echo $this->baseUrl()?>/img/cursoEjecutivo.png" alt="">
									<div class="carousel-caption">
									  <h4>Curso Ejecutivo</h4>
									  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. </p>
									</div>
								  </div>
								  <div class="item">
									<img src="<?php echo $this->baseUrl()?>/img/cursosPresencialesVirtuales.png" alt="">
									<div class="carousel-caption">
									  <h4>Cursos Virtuales y Presenciales</h4>
									  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. </p>
									</div>
								  </div>
								  <div class="item">
									<img src="<?php echo $this->baseUrl()?>/img/access.png" alt="">
									<div class="carousel-caption">
									  <h4>Curso Acces 2010</h4>
									  <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. </p>
									</div>
								  </div>
								</div>
								<a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
								<a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
							</div>
						</div>
					</div>
				  </div>
				  
				</div> 
				<br>
				<div class="row-fluid">
					<div style="margin-left: 72px;">
						<ul class="thumbnails">
						   <li class="span3">
							<div class="thumbnail">
							  <img src="<?php echo $this->baseUrl()?>/img/about.jpg" alt="">
							  <div class="caption">
								<h3>Quienes Somos</h3>
								<p>c id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
								<p><a href="#" class="btn btn-primary">Más...</a></p>
							  </div>
							</div>
						  </li>
						   <li class="span3">
							<div class="thumbnail">
							  <img src="<?php echo $this->baseUrl()?>/img/cursos.jpg" alt="">
							  <div class="caption">
								<h3>Cursos</h3>
								<p>c id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
								<p><a href="#" class="btn btn-primary">Más...</a></p>
							  </div>
							</div>
						  </li>
						  <li class="span3">
							<div class="thumbnail">
							  <img src="<?php echo $this->baseUrl()?>/img/instructor.jpg" alt="">
							  <div class="caption">
								<h3>Instructores</h3>
								<p>c id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
								<p><a href="#" class="btn btn-primary">Más...</a></p>
							  </div>
							</div>
						  </li>
						 <li class="span3">
							<div class="thumbnail">
							  <img src="<?php echo $this->baseUrl()?>/img/aulaVirtual.jpg" alt="">
							  <div class="caption">
								<h3>Aula Virtual</h3>
								<p>c id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
								<p><a href="#" class="btn btn-primary">Más...</a></p>
							  </div>
							</div>
						  </li>
						</ul>
					</div>
				 </div>
		  
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
	<footer>
	<div class="container">
		<hr>
	
        <p>© Copyright 2012</p>
     
	</div>
	 </footer>
	
</html>