<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Perfil</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Ajustes - Victor Araya Jiménez</h1>
						<p class="text-info">Cuenta de tipo: Administrador</p><br>
						<ul class="thumbnails">
							<li class="span2">
							  <div class="thumbnail">
								<img src="http://placehold.it/260x180" alt="">
								<div class="caption">
								  <p>Cambiar foto</p>
								  <p><a href="#" class="btn btn-primary">Acceder</a></p>
								</div>
							  </div>
							</li>
							<li class="span2">
							  <div class="thumbnail">
								<img src="http://placehold.it/260x180" alt="">
								<div class="caption">
								  <p>Cambiar Clave</p>
								  <p><a href="#" class="btn btn-primary">Acceder</a></p>
								</div>
							  </div>
							</li>
							<li class="span2">
							  <div class="thumbnail">
								<img src="http://placehold.it/260x180" alt="">
								<div class="caption">
								  <p>Actualizar Datos</p>
								  <p><a href="#" class="btn btn-primary">Acceder</a></p>
								</div>
							  </div>
							</li>
						  </ul>
					</div>
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>