<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Perfil</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Victor Araya Jiménez</h1>
						<p class="text-info">Cuenta de tipo: Administrador</p><br><br>
						<form class="form-horizontal">
							<fieldset>
						
							 <ul class="thumbnails" style="    margin-left: 473px;    overflow: hidden;    position: absolute;    margin-top: -55px;">
								<li class="span2">
									<img src="http://placehold.it/160x120" alt="">
								 </li>
								
							  </ul>
								<div class="control-group">
								<label class="control-label" for="input01">Fecha Ingreso: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="15 Julio 2009" class="input-xlarge" id="input01"></div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="input01">Codigo: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="459684" class="input-small" id="input01"></div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="input01">Cedula: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="206860157" class="input-xlarge" id="input01"></div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="input01">Genero: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="Masculino" class="input-xlarge" id="input01"></div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="input01">Edad: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="19" class="input-small" id="input01"></div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="input01">Correo: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="vic9511@hotmail.com" class="input-xlarge" id="input01"></div>
							  </div>
							   <div class="control-group">
								<label class="control-label" for="input01">Telefonos: </label>
								<div class="controls">  
									<input readonly="readonly" type="text" value="2430-4654" class="input-small" id="input01">
									<input readonly="readonly" type="text" value="70101918" class="input-small" id="input01">
								</div>
							  </div>
							   <div class="control-group">
								<label class="control-label" for="input01">Dirección: </label>
								<div class="controls">  <input readonly="readonly" type="text" value="50 este tios bar calle loria, Itiquis" class="input-xlarge" id="input01"></div>
							  </div>
							</fieldset>
						  </form>
					</div>
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>