<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Mensajes</title>
		<link rel="shortcut icon" href="img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Agregar Componentes !!!</h1>
						<p class="text-info">Agrega cursos, horarios, grupos y modulos a continuación.</p><br>
						<div class="span9">
			
						  <ul class="thumbnails">
							<li class="span5">
							  <a href="<?php echo $this->baseUrl()?>/agregar/curso" class="thumbnail">
								<img src="<?php echo $this->baseUrl()?>/img/addCursos.png" alt="">
							  </a>
							</li>
							<li class="span5">
							  <a href="<?php echo $this->baseUrl()?>/agregar/modulo" class="thumbnail">
								<img src="<?php echo $this->baseUrl()?>/img/addModulos.png" alt="">
							  </a>
							</li>
							<li class="span5">
							  <a href="<?php echo $this->baseUrl()?>/agregar/grupo" class="thumbnail">
								<img src="<?php echo $this->baseUrl()?>/img/addGrupo.png" alt="">
							  </a>
							</li>
							<li class="span5">
							  <a href="<?php echo $this->baseUrl()?>/agregar/horario" class="thumbnail">
								<img src="<?php echo $this->baseUrl()?>/img/addHorario.png" alt="">
							  </a>
							</li>
						  </ul>
						</div>
						
					</div>
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>