<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Agegar Curso</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Agrega un nuevo grupo !!!</h1>
						<p class="text-info">Llena los siguientes campos con los datos del Grupo.</p>
						
						
						<form class="form-horizontal" action="" method="POST">
							<fieldset>
							  <br><br>
								<div class="control-group success">
									<label class="control-label" for="user">Codigo: </label>
									<div class="controls">
									  <input type="text" class="input-xlarge" id="user">
									  <span class="help-inline">Habilitado!</span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="horario">Horario: </label>
									<div class="controls">
									 <select class="span5" id="horario">
										<option>- -  Seleccione un horario - - </option>
										<option>Martes 8 a 11</option>
										<option>Martes 11 a 2</option>
										<option>Martes 2 a 5</option>
										<option>Marttes 6 a 9</option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="curso">Curso: </label>
									<div class="controls">
									 <select class="span5" id="curso">
										<option>- -  Seleccione un Curso - - </option>
										<option>Operador en Sistemas Informáticos</option>
										<option>Técnico Operador en Sistemas Informáticos</option>
										<option>Mantenimiento y Reparación</option>
										<option>Excel Avanzado VBA</option>
										<option>Diseño de Paginas Web</option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="modulos">Profesor: </label>
									<div class="controls">
										<select class="span5" id="curso">
										<option>- -  Seleccione un profesor - - </option>
										<option>Juan Araya Mesen</option>
										<option>Ismael Artavia </option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="modulos">Modulo Inicial: </label>
									<div class="controls">
										<select class="span5" id="curso">
										<option>- -  Seleccione un Modulo - - </option>
										<option>Windows 7</option>
										<option>MS Office Word 2010</option>
										<option>MS Office Excel 2010</option>
										<option>MS Office PP 2010</option>
										<option>MS Office Publisher 2010</option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="modulos">Modulo Siguiente: </label>
									<div class="controls">
										<select class="span5" id="curso">
										<option>- -  Seleccione un Modulo - - </option>
										<option>Windows 7</option>
										<option>MS Office Word 2010</option>
										<option>MS Office Excel 2010</option>
										<option>MS Office PP 2010</option>
										<option>MS Office Publisher 2010</option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="nombreCompleto">Fecha Inicio: </label>
									<div class="controls">  
										<div class="input-append date" id="dp2" data-date="10-27-2012" data-date-format="dd-mm-yyyy">
													<input class="span9" size="16" type="text" value="10-27-2012" readonly="" >
													<span class="add-on"><i class="icon-calendar"></i></span>
												 </div>
										
									</div>
								</div>	
								
								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Completar Registro</button>
								</div>
							</fieldset>
						</form>


					</div>
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>