<!DOCTYPE html>
<html>
    <head>
        <title>IMEC. | Agegar Curso</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/img/icono.png"/>
        <!-- Styles -->
        <?php echo $this->partial("partials/all-styles.phtml") ?>
        <!-- Styles -->
    </head>
    <body>
        <div id="encabezado">
            <?php echo $this->partial("partials/top-bar.phtml") ?>
        </div>
        <div id="contenido">
            <div class="container">
                <div class="container-fluid">
                    <div class="row-fluid">
                        <?php echo $this->partial("partials/menu-lat.phtml") ?>
                        <div class="span9">
                            <h1>Agrega un nuevo curso !!!</h1>
                            <p class="text-info">Llena los siguientes campos con los datos del Curso.</p>

                            <?php
                            if ($this->post == true) {
                                if (count($this->errors) > 0) {  ?>
                                    <form class="form-horizontal" action="" method="POST">
                                        <fieldset>
                                            <br><br>
                                            <?php 
                                            if (in_array("codigo", $this->errors)) {?>
                                                 <div class="control-group error">
                                                   <label class="control-label" for="user">Codigo: </label>
                                                   <div class="controls">
                                                       <input type="text" class="input-xlarge" name="codigo" value="<?php echo $this->curso['codigo'];?>" id="user">
                                                       <span class="help-inline">Campo Requerido!</span>
                                                   </div>
                                                   
                                                 </div>
                                            <?php
                                            }else{?>
                                                 <div class="control-group success">
                                                   <label class="control-label" for="user">Codigo: </label>
                                                   <div class="controls">
                                                       <input type="text" class="input-xlarge" name="codigo" value="<?php echo $this->curso['codigo'];?>" id="user">
                                                        <span class="help-inline">  ok!</span>
                                                   </div>
                                                   
                                                 </div>  
                                            <?php }
                                            ?>
                                            <div class="control-group">
                                                <label class="control-label" for="nombreCompleto">Nombre Curso: </label>
                                                <div class="controls">  
                                                    <input type="text" placeholder="Nombre" value="<?php echo $this->curso['nombre'];?>" name="nombre" class="input-medium" id="nombre">

                                                </div>
                                            </div>	

                                            <div class="control-group">
                                                <label class="control-label" for="comentario">Descripcion del Curso: </label>
                                                <div class="controls">
                                                    <textarea class="input-xlarge"  name="descripcion" id="comentario" rows="3"><?php echo $this->curso['descripcion'];?></textarea>
                                                </div>
                                            </div>

                                            <div class="form-actions">
                                                <button type="submit" class="btn btn-primary">Agegar Curso</button>
                                            </div>
                                        </fieldset>
                                    </form>
                                    <?php
                                }
                            } else {
                                echo'
                                              <form class="form-horizontal" action="" method="POST">
							<fieldset>
							  <br><br>
							  <div class="control-group success">
                                                              <label class="control-label" for="user">Codigo: </label>
                                                              <div class="controls">
									  <input type="text" class="input-xlarge" name="codigo" id="user">
									  <span class="help-inline">Habilitado!</span>
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label" for="nombreCompleto">Nombre Curso: </label>
									<div class="controls">  
										<input type="text" placeholder="Nombre"  name="nombre" class="input-medium" id="nombre">
										
									</div>
								</div>	
							
								<div class="control-group">
									<label class="control-label" for="comentario">Descripcion del Curso: </label>
									<div class="controls">
										<textarea class="input-xlarge"  name="descripcion" id="comentario" rows="3"></textarea>
									</div>
								</div>

								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Agegar Curso</button>
								</div>
							</fieldset>
						</form>
                                               ';
                            }
                            ;
                            ?>     

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- all scripts -->
        <?php echo $this->partial("partials/all-scripts.phtml") ?>
        <!-- all scripts -->
    </body>
</html>