<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Registro</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Formulario de Registro !!!</h1>
						<p class="text-info">Llena la Siguiente información para completar el registro.</p>
						
						
						<form class="form-horizontal" action="<?php echo $this->baseUrl()?>/registro/result" method="POST">
							<fieldset>
							  <br><br>
								<div class="control-group">
									<label class="control-label" for="nombreCompleto">Nombre Completo: </label>
									<div class="controls">  
										<input type="text" placeholder="Nombre" class="input-medium" id="nombre">
										<input type="text" placeholder="Primer Apellido" class="input-medium" id="apellido1">	
										<input type="text" placeholder="Segundo Apellido" class="input-medium" id="apellido2">
									</div>
								</div>	
								<div class="control-group">
									<label class="control-label" for="fileInput">Subir foto</label>
									<div class="controls">
									  <input class="input-file" id="fileInput" type="file">
									</div>
								  </div>
								<div class="control-group">
									<label class="control-label">Genero</label>
									<div class="controls">
									  <div class="btn-group" data-toggle="buttons-radio">
										  <button type="button"  class="btn active">Masculino</button>
										  <button type="button"  class="btn">Femenino</button>
										</div>
									</div>
								</div>
									
								<div class="control-group">
									<label class="control-label" for="curso">Tipo de Usuario: </label>
									<div class="controls">
									 <select class="span3" id="curso">
										<option>Estudiante</option>
										<option>Profesor</option>
										<option>Administrativo</option>
										<option>Vendedor</option>
										<option>Gerencia</option>
									  </select>
									  <span class="help-inline"></span>
									</div>
								</div>
								
								<div class="control-group success">
									<label class="control-label" for="user">Usuario: </label>
									<div class="controls">
									  <input type="text" class="input-xlarge" id="user">
									  <span class="help-inline">Habilitado!</span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="cedula">Cedula: </label>
									<div class="controls">
									  <input type="text" class="input-xlarge" id="cedula">
									  <span class="help-inline"></span>
									</div>
								</div>
								<div class="control-group">
									<label class="control-label" for="fecNac">Fecha Nacimiento: </label>
									<div class="controls">
									  <div class="input-append date" id="dp1" data-date="1-1-1980" data-date-format="dd-mm-yyyy">
													<input class="span9" size="16" type="text" value="1-1-1980" readonly="" >
													<span class="add-on"><i class="icon-calendar"></i></span>
												 </div>
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label" for="telefonos">Telefonos: </label>
									<div class="controls">
										<input type="text" placeholder="Habitación" class="input-medium" id="hab">
										<input type="text" placeholder="Celular" class="input-medium" id="cel">	
										<input type="text" placeholder="Trabajo" class="input-medium" id="trab">
										<span class="help-inline"></span>
									</div>
								</div>
								
								<div class="control-group">
									<label class="control-label" for="direc">Dirección: </label>
									<div class="controls">
									  <input type="text" class="input-xlarge" id="direc">
									  <span class="help-inline"></span>
									</div>
								</div>
					
								<div class="control-group">
									<label class="control-label" for="comentario">Cometario Especifico: </label>
									<div class="controls">
										<textarea class="input-xlarge" id="comentario" rows="3"></textarea>
									</div>
								</div>

								<div class="form-actions">
									<button type="submit" class="btn btn-primary">Completar Registro</button>
								</div>
							</fieldset>
						</form>


					</div>
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>