<!DOCTYPE html>
<html>
    <head>
        <title>IMEC. | Agegar Curso</title>
        <link rel="shortcut icon" href="<?php echo $this->baseUrl() ?>/img/icono.png"/>
        <!-- Styles -->
        <?php echo $this->partial("partials/all-styles.phtml") ?>
        <!-- Styles -->
    </head>
    <body>
        <div id="encabezado">
            <?php echo $this->partial("partials/top-bar.phtml") ?>
        </div>
        <div id="contenido">
            <div class="container">
                <div class="container-fluid">
                    <div class="row-fluid">
                        <?php echo $this->partial("partials/menu-lat.phtml") ?>
                        <div class="span9">
                            <h1>Agrega un nuevo modulo !!!</h1>
                            <p class="text-info">Llena los siguientes campos con los datos del Modulo.</p>

                             <?php
                             if ($this->post == true) {
                                if (count($this->errors) > 0) {
                                    ?>
                                    <form class="form-horizontal" action="" method="POST">
                                        <fieldset>
                                            <br><br>
                        <!--  **********************************  VALIDO SI EL CODIGO CONTIENE ERRORES ***********    -->
                                            <?php if (in_array("codigo", $this->errors)) { ?>
                                                <div class="control-group error">
                                                    <label class="control-label" for="user">Codigo: </label>
                                                    <div class="controls">
                                                        <input type="text" class="input-xlarge" name="codigo" value="<?php echo $this->misModulos['codigo']; ?>" >
                                                        <span class="help-inline">Campo Requerido!</span>
                                                    </div>
                                                </div>
                                            <?php } else { ?>
                                                <div class="control-group success">
                                                    <label class="control-label" for="user">Codigo: </label>
                                                    <div class="controls">
                                                        <input type="text" class="input-xlarge" name="codigo" value="<?php echo $this->misModulos['codigo']; ?>">
                                                        <span class="help-inline">Ok!</span>
                                                    </div>
                                                </div>
                                            <?php } ?>
                        <!--  **********************************  VALIDO SI EL NOMBRE CONTIENE ERRORES ***********    -->
                                            <?php if (in_array("nombre", $this->errors)) { ?>
                                                <div class="control-group error">
                                                    <label class="control-label" for="nombreCompleto">Nombre Curso: </label>
                                                    <div class="controls">  
                                                        <input type="text" placeholder="Nombre" class="input-medium" name="nombre" value="<?php echo $this->misModulos['nombre']; ?>">
                                                         <span class="help-inline">Campo Requerido!</span>
                                                    </div>
                                                </div>	
                                             <?php } else { ?>
                                                <div class="control-group">
                                                    <label class="control-label" for="nombreCompleto">Nombre Curso: </label>
                                                    <div class="controls">  
                                                        <input type="text" placeholder="Nombre" class="input-medium" name="nombre" value="<?php echo $this->misModulos['nombre']; ?>">

                                                    </div>
                                                </div>
                                            <?php } ?>
                        <!--  **********************************  VALIDO SI LA DESCRIPCION CONTIENE ERRORES ***********    -->
                                              <?php if (in_array("descripcion", $this->errors)) { ?>
                                               <div class="control-group error">
                                                    <label class="control-label" for="comentario">Descripcion del Curso: </label>
                                                    <div class="controls">
                                                        <textarea class="input-xlarge" name="descripcion" rows="3"><?php echo $this->misModulos['descripcion']; ?></textarea>
                                                         <span class="help-inline">Campo Requerido!</span>
                                                    </div>
                                                </div>	
                                             <?php } else { ?>
                                                <div class="control-group">
                                                    <label class="control-label" for="comentario">Descripcion del Curso: </label>
                                                    <div class="controls">
                                                        <textarea class="input-xlarge" name="descripcion" rows="3"><?php echo $this->misModulos['descripcion']; ?></textarea>
                                                    </div>
                                                </div>
                                            <?php } ?>
                        <!--  **********************************  VALIDO SI EL CURSO CONTIENE ERRORES ***********    -->
                                             <?php if (in_array("cursos_codigo", $this->errors)) { ?>
                                              <div class="control-group error">
                                                    <label class="control-label" for="curso">Curso al que pertenece: </label>
                                                    <div class="controls">
                                                        <select class="span5" name="cursos_codigo">
                                                             <option value=""> --- Selecciones un Curso --- </option>      
                                                             <?php
                                                                if (count($this->misCursos)) {
                                                                    foreach ($this->misCursos as $row) {
                                                                        echo "
                                                                          <option value='" . $row->codigo . "'>" . $row->nombre . "</option>      
                                                                        ";
                                                                    }
                                                                }
                                                             ?> 
                                                        </select>
                                                        <span class="help-inline">Campo Requerido!</span>
                                                    </div>
                                                </div>
                                             <?php } else { ?>
                                                <div class="control-group">
                                                    <label class="control-label" for="curso">Curso al que pertenece: </label>
                                                    <div class="controls">
                                                        <select class="span5" name="cursos_codigo">
                                                             <option value="<?php echo $this->cursoSelect['codigo']; ?>"> <?php echo $this->cursoSelect['nombre']; ?> </option>      
                                                             <?php
                                                                if (count($this->misCursos)) {
                                                                    foreach ($this->misCursos as $row) {
                                                                        echo "
                                                                          <option value='" . $row->codigo . "'>" . $row->nombre . "</option>      
                                                                        ";
                                                                    }
                                                                }
                                                             ?> 
                                                        </select>
                                                    </div>
                                                </div>
                                            <?php } ?>
                                            
                                            <div class="form-actions">
                                                <button type="submit" class="btn btn-primary">Completar Registro</button>
                                            </div>
                                        </fieldset>
                                    </form>
                                    <?php
                                }
                             } else { 
                                 ?>    
                                    <form class="form-horizontal" action="" method="POST">
                                        <fieldset>
                                            <br><br>
                                            <div class="control-group">
                                                <label class="control-label" for="user">Codigo: </label>
                                                <div class="controls">
                                                    <input type="text" class="input-xlarge" name="codigo">
                                                    <span class="help-inline"></span>
                                                </div>
                                            </div>

                                            <div class="control-group">
                                                <label class="control-label" for="nombreCompleto">Nombre Curso: </label>
                                                <div class="controls">  
                                                    <input type="text" placeholder="Nombre" class="input-medium" name="nombre">

                                                </div>
                                            </div>	

                                            <div class="control-group">
                                                <label class="control-label" for="comentario">Descripcion del Curso: </label>
                                                <div class="controls">
                                                    <textarea class="input-xlarge" name="descripcion" rows="3"></textarea>
                                                </div>
                                            </div>
                                            <div class="control-group">
                                                <label class="control-label" for="curso">Curso al que pertenece: </label>
                                                <div class="controls">
                                                    <select class="span5" name="cursos_codigo">
                                                         <option value=""> --- Selecciones un Curso --- </option>      
                                                         <?php
                                                            if (count($this->misCursos)) {
                                                                foreach ($this->misCursos as $row) {
                                                                    echo "
                                                                      <option value='" . $row->codigo . "'>" . $row->nombre . "</option>      
                                                                    ";
                                                                }
                                                            }
                                                         ?> 
                                                    </select>
                                                    <span class="help-inline"></span>
                                                </div>
                                            </div>
                                            <div class="form-actions">
                                                <button type="submit" class="btn btn-primary">Completar Registro</button>
                                            </div>
                                        </fieldset>
                                    </form>
                                 <?php
                             }
                             ?>      
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- all scripts -->
        <?php echo $this->partial("partials/all-scripts.phtml") ?>
        <!-- all scripts -->
    </body>
</html>