<!DOCTYPE html>
<html>
	<head>
		<title>IMEC. | Facturación</title>
		<link rel="shortcut icon" href="img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
						<h1>Historial Factura #456</h1>
						<p class="text-info">Victor Araya Jiménez Cod# 546</p>
						
						<br>
						<h3>Historial de Abonos a esta factura</h3>
						<br>		
						<table class="bordered" >
							<tr>
								<th># Abono.</th>
								<th>Nombre</th>
								<th>Fecha Abono</th>
								<th>Monto</th>
								<th>Accion</th>
							</tr>

							<tr>
								<td>65469</td>
								<td>Victor Araya</td>
								<td>15/5/2012</td>
								<td>¢5000</td>
								<td ><a href="<?php echo $this->baseUrl()?>/facturar/result?id=78628173"><i class="icon-zoom-in"> </i> Ver recibo</a></td>
							</tr>
							<tr>
								<td>65469</td>
								<td>Victor Araya</td>
								<td>15/4/2012</td>
								<td>¢15000</td>
								<td ><a href="<?php echo $this->baseUrl()?>/facturar/result?id=78628173"><i class="icon-zoom-in"> </i> Ver recibo</a></td>
							</tr>
						</table>
						<br>
									
					</div>
					
					
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>