<!DOCTYPE html>
<html>
	<head>
            <title>IMEC. | Facturaci&oacute;n</title>
		<link rel="shortcut icon" href="<?php echo $this->baseUrl()?>/img/icono.png"/>
		<!-- Styles -->
			<?php echo $this->partial("partials/all-styles.phtml") ?>
		<!-- Styles -->
	</head>
	<body>
		<div id="encabezado">
			<?php echo $this->partial("partials/top-bar.phtml") ?>
		</div>
		<div id="contenido">
			<div class="container">
				<div class="container-fluid">
				<div class="row-fluid">
					<?php echo $this->partial("partials/menu-lat.phtml") ?>
					<div class="span9">
                                            <h1>Buscar Estudiante !!!</h1>
                                            <p class="text-info">Busca el estudiante deseado y realiaza el tramite correspondiente.</p>
						<br>
						
						<form method="get" class="form-horizontal">
                                                    <select name="tipo" class="span3"  id="select01">
                                                        <option value="1">Nombre</option>
                                                        <option value="2">Cedula</option>
                                                        <option value="3">Usuario</option>
                                                    </select>



                                                    <input type="text" name="id" class="span4" placeholder="Digite el termino de busqueda"/>
                                                    <input type="hidden" name="next" value="<?php echo $this->next;?>" />

                                                    <button type="submit" class="btn btn-primary">Filtrar</button>

                                                </form> 
						
						<table class="bordered" >
                                                    <tr>
                                                        <th>Cod.</th>
                                                        <th>Nombre</th>
                                                        <th>C&eacute;dula</th>
                                                        <th>Edad</th>
                                                        <th>Telefono</th>
                                                        <th>Fecha Ingr.</th>
                                                        <th>Acci&oacute;n</th>
                                                    </tr>
                                                    <?php
                                                    if (count($this->miEstudiante)) {
                                                        foreach ($this->miEstudiante as $row) {
                                                            echo "
                                                                     <tr>
                                                                        <td>" . $row->id . "</td>
                                                                        <td>" . $row->nombre . " " . $row->apellido1 . "</td>
                                                                        <td>" . $row->identificacion . "</td>
                                                                        <td>" . $row->getEdad() . "</td>
                                                                        <td>" ; 
                                                                             if (count($this->telefonos_model->getTelefonos($row->id))) {
                                                                                 foreach ($this->telefonos_model->getTelefonos($row->id) as $tel) 
                                                                                     echo $tel->numeroTelefono;
                                                                             }else{
                                                                                 foreach ($this->telefonos_model->getTelefonos($row->id) as $tel) 
                                                                                      echo "* " . $tel->numeroTelefono . " ";
                                                                             }

                                                                  echo "</td>
                                                                        <td>" . $row->getFechaRegistro() . "</td>
                                                                        ";
                                                                        if($this->next == "matricular"){
                                                                            echo"
                                                                                <td > <a href='" . $this->baseUrl() . "/matricular/matricular?id=" . $row->id . "'><i class='icon-th-list'> </i> Matricular </a></td>
                                                                             ";
                                                                        }else{
                                                                            if($this->next == "facturar"){
                                                                            echo"
                                                                                 <td ><a href='" . $this->baseUrl() . "/facturar/detalle?id=" . $row->id . "'><i class='icon-folder-open'> </i> Facturas </a></td>
                                                                             ";
                                                                            }else{
                                                                                if($this->next == "consultar"){
                                                                                    echo"
                                                                                            <td ><a href='" . $this->baseUrl() . "/estudiantes/info?id=" . $row->id . "'><i class='icon-zoom-in'> </i> Mas..</a></td>
                                                                                        ";
                                                                                }else{
                                                                                    $a = $this->baseUrl();
                                                                                    header ("Location: $a/");
                                                                                }
                                                                            }
                                                                        }
                                                                        echo"
                                                                       
                                                                        </tr>
                                                                ";
                                                        } 
                                                    } else {
                                                        if (count($this->estSer)) {
                                                              foreach ($this->estSer as $row) {
                                                                echo "
                                                                   <tr>
                                                                        <td>" . $row->id . "</td>
                                                                        <td>" . $row->nombre . " " . $row->apellido1 . "</td>
                                                                        <td>" . $row->identificacion . "</td>
                                                                        <td>" . $row->getEdad() . "</td>
                                                                        <td>" ; 
                                                                             if (count($this->telefonos_model->getTelefonos($row->id)) == 1 ) {
                                                                                 foreach ($this->telefonos_model->getTelefonos($row->id) as $tel) 
                                                                                     echo $tel->numeroTelefono;
                                                                             }else{
                                                                                 foreach ($this->telefonos_model->getTelefonos($row->id) as $tel) 
                                                                                     echo "* " . $tel->numeroTelefono . " ";
                                                                             }        
                                                                  echo "</td>    
                                                                        <td>" . $row->getFechaRegistro() . "</td>
                                                                        ";
                                                                        if($this->next == "matricular"){
                                                                            echo"
                                                                                <td > <a href='" . $this->baseUrl() . "/matricular/matricular?id=" . $row->id . "'><i class='icon-th-list'> </i> Matricular </a></td>
                                                                             ";
                                                                        }else{
                                                                            if($this->next == "facturar"){
                                                                            echo"
                                                                                 <td ><a href='" . $this->baseUrl() . "/facturar/detalle?id=" . $row->id . "'><i class='icon-folder-open'> </i> Facturas </a></td>
                                                                             ";
                                                                            }else{
                                                                                if($this->next == "consultar"){
                                                                                    echo"
                                                                                            <td ><a href='" . $this->baseUrl() . "/estudiantes/info?id=" . $row->id . "'><i class='icon-zoom-in'> </i> Mas..</a></td>
                                                                                        ";
                                                                                }else{
                                                                                    $a = $this->baseUrl();
                                                                                    header ("Location: $a/");
                                                                                }
                                                                            }
                                                                        }
                                                                        echo"
                                                                    </tr>
                                                                    ";
                                                            }
                                                        }else{
                                                            echo "
                                                                     <tr>
                                                                        <td colspan='7'>No se encontraron registros</td>
                                                                      </tr>
                                                                ";
                                                        }    
                                                    }
                                                    ?>   
                                                </table>
                                                
                                                
						
						
					</div>
					
					
				</div>
				</div>
			</div>
		</div>
		<!-- all scripts -->
			<?php echo $this->partial("partials/all-scripts.phtml") ?>
		<!-- all scripts -->
	</body>
</html>