
			<div class="navbar navbar-fixed-top  navbar-inverse">
				<div class="navbar-inner">
				  <div class="container">
					<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					</a>
						<a href="<?php echo $this->baseUrl()?>/home/logout"><img class="img-titulo"  src="<?php echo $this->baseUrl()?>/img/logoImec.png" /> </a>
					<div class="nav-collapse">
					  <ul class="nav">
						
						<li><a data-toggle="modal" href="#contacto"><i class="icon-flag"></i> Contactenos</a></li>
						
					
					  </ul>
					  
					  <ul class="nav pull-right">
					
					  <li class="divider-vertical"></li>
						
						<li class="dropdown">
						  <a data-toggle="dropdown" class="dropdown-toggle" href="#">Login <b class="caret"></b></a>
						  <ul class="dropdown-menu">
							<form method="post" action="<?php echo $this->baseUrl()?>/home/" style="margin-left: 12px;margin-top: 14px;margin-right: 12px;" class="bs-docs-example form-horizontal">								<div class="control-group">
								  
									<input type="text" id="inputEmail" placeholder="Email" class="span3">
							
								</div>
								<div class="control-group">
								
									<input type="password" id="inputPassword" placeholder="Password" class="span3">
								 
								</div>
								<div class="control-group">
								
									<label class="checkbox">
									  <input type="checkbox"> Remember me
									</label>
									<button type="submit" class="btn">Sign in</button>
								
								</div>
							  </form>
						  </ul>
						</li>
						
					  </ul>
					   <form  action="" method="get" class="navbar-search pull-right">
							<input type="hidden" value="1" name="type-search">
							<input type="text" placeholder="Buscar Cursos" name="termino-search" class="search-query span4">
					  </form>
					  
					  
					</div><!-- /.nav-collapse -->
				  </div>
				</div><!-- /navbar-inner -->
			</div>

			

<div id="contacto" class="modal hide fade in" style="display: none; ">					

  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
    <h3>Envia tu mensaje a continuación	</h3>
  </div>
	
	<form method="post" class="form-horizontal">
		<div class="modal-body">
			<fieldset>
		  
			  <div class="control-group">
				<label class="control-label">Tipo de Consulta: </label>
				<div class="controls docs-input-sizes">
					<select name="tipoConsulta" class="span3">
						<option></option>
						<option>Duda Administrativa</option>
						<option>Consulta de Estudiante</option>
						<option>Información Sobre algun Curso</option>
						<option>Otros</option>
					</select>
				</div>
			  </div>
			  
			   <div class="control-group">
				<label class="control-label">Redacta tu mensaje: </label>
				<div class="controls docs-input-sizes">
				 <textarea name="consulta"class="input-xlarge" id="textarea" rows="3"></textarea>
				  <p class="help-block">Atenderemos tu consulta lo mas pronto posible. Gracias!</p>
				</div>
			  </div>
			 
			</fieldset>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">Cerrar</a>
			<button type="submit" class="btn btn-primary">Enviar Mensaje</button>
		</div>
	</form>
</div>