<div class="navbar navbar-fixed-top  navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<a data-target=".nav-collapse" data-toggle="collapse" class="btn btn-navbar">
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</a>
			<a href="<?php echo $this->baseUrl()?>/"><img class="img-titulo"  src="<?php echo $this->baseUrl()?>/img/titulo.png" /> </a>
			<div class="nav-collapse">
				<ul class="nav">
					<li><a href="<?php echo $this->baseUrl()?>/">Home</a></li>
					<li><a href="<?php echo $this->baseUrl()?>/mensajes/">Mensajes</a></li>
				</ul>
				<ul class="nav pull-right">
					<li class="dropdown">
						<a data-toggle="dropdown" class="dropdown-toggle" href="#">Mi Perfill <b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="<?php echo $this->baseUrl()?>/perfil/"><i class="icon-user"></i> Perfil</a></li>
							<li><a href="<?php echo $this->baseUrl()?>/perfil/ajustes"><i class="icon-cog"></i> Ajustes</a></li>
							<li class="divider"></li>
							<li><a data-toggle="modal" href="#help"><i class="icon-flag"></i> Ayuda</a></li>
						</ul>
					</li>
					<li class="divider-vertical"></li>
					<li><a href="<?php echo $this->baseUrl()?>/home/logout">Salir</a></li>
				</ul>
				<form  action="<?php echo $this->baseUrl()?>/estudiantes/search" method="get" class="navbar-search pull-right">
					<input type="hidden" value="1" name="type-search">
					<input type="text" placeholder="Buscar Estudiante" name="termino-search" class="search-query span2">
				</form>
			</div><!-- /.nav-collapse -->
		</div>
	</div><!-- /navbar-inner -->
</div>

<div id="help" class="modal hide fade in" style="display: none; ">					
	<div class="modal-header">
		<a class="close" data-dismiss="modal">×</a>
		<h3>Nesesitas Ayuda?	</h3>
	</div>
	<div class="modal-body">
		<p>Aqui encontraras preguntas frecuentes que te pueden ayudar con tu problema, De lo contrario dirijete a contactar gerencia y te ayudaremos con gusto.</p>
		<div class="tabbable" style="margin-bottom: 9px;">
			<ul class="nav nav-tabs">
				<li class="active"><a href="#1" data-toggle="tab">Matricular Estudiante</a></li>
				<li class=""><a href="#2" data-toggle="tab">Administrativo</a></li>
				<li class=""><a href="#3" data-toggle="tab">Facturación</a></li>
				<li class=""><a href="#4" data-toggle="tab">Inf. de Usuarios</a></li>
			</ul>
			<div class="tab-content">
				<div class="tab-pane active" id="1">
					<p>Estoy en la sección 1.</p>
					<p>Estoy en la sección 1.</p>  
					<p>Estoy en la sección 1.</p>  
					<p>Estoy en la sección 1.</p>  
					<p>Estoy en la sección 1.</p>  
					<p>Estoy en la sección 1.</p>
				</div>
				<div class="tab-pane" id="2">
					<p>Hola, estoy en la sección 2.</p>
					<p>Hola, estoy en la sección 2.</p>
					<p>Hola, estoy en la sección 2.</p>
					<p>Hola, estoy en la sección 2.</p>
					<p>Hola, estoy en la sección 2.</p>
					<p>Hola, estoy en la sección 2.</p>
				</div>
				<div class="tab-pane" id="3">
					<p>Esto es la sección 3.</p>
					<p>Esto es la sección 3.</p>
					<p>Esto es la sección 3.</p>
					<p>Esto es la sección 3.</p>
					<p>Esto es la sección 3.</p>
					<p>Esto es la sección 3.</p>
				</div>
				<div class="tab-pane" id="4">
					<p>Esto es la sección 4.</p>
					<p>Esto es la sección 4.</p>
					<p>Esto es la sección 4.</p>
					<p>Esto es la sección 4.</p>
					<p>Esto es la sección 4.</p>
					<p>Esto es la sección 4.</p>
				</div>
			</div>
		</div>
	</div>
	<div class="modal-footer">
		<a href="#" class="btn btn-primary" data-dismiss="modal">Salir</a>
	</div>

</div>			